/* eslint-disable @typescript-eslint/explicit-module-boundary-types */
/* eslint-disable @typescript-eslint/no-explicit-any */
import { SWRConfig, useGetRequest } from "./useGetRequest";
import { ResponseError } from "../types";
import { AxiosRequestConfig, AxiosResponse } from "axios";
import { SWRMutationConfig, useMutationRequest } from "src/request/useMutationRequest";

/*
 *  this file is generated by @openapi-integration/swr-request-generator.
 *  please do not modify it manually.
 */
export const useMobileDetailV2apiAireVerificationFreinRequest = (
  {
    id,
    language,
  }: {
    id: number;
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseAireVerificationFreinData, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseAireVerificationFreinData, ResponseError>(
    {
      url: `/${language}/api/v2/mobileDetail/AireVerificationFrein/${id}`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileDetailV2apiAutre511Request = (
  {
    id,
    language,
  }: {
    id: number;
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseAutre511data, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseAutre511data, ResponseError>(
    {
      url: `/${language}/api/v2/mobileDetail/Autre511/${id}`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileDetailV2apiCameraRequest = (
  {
    id,
    language,
  }: {
    id: number;
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseCameraData, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseCameraData, ResponseError>(
    {
      url: `/${language}/api/v2/mobileDetail/Camera/${id}`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileDetailV2apiCamionnageInterdictionRequest = (
  {
    id,
    language,
  }: {
    id: number;
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseBaseData, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseBaseData, ResponseError>(
    {
      url: `/${language}/api/v2/mobileDetail/CamionnageInterdiction/${id}`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileDetailV2apiCamionnageLimiteLegaleRequest = (
  {
    id,
    language,
  }: {
    id: number;
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseBaseData, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseBaseData, ResponseError>(
    {
      url: `/${language}/api/v2/mobileDetail/CamionnageLimiteLegale/${id}`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileDetailV2apiCamionnageLimitePoidsRequest = (
  {
    id,
    language,
  }: {
    id: number;
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseBaseData, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseBaseData, ResponseError>(
    {
      url: `/${language}/api/v2/mobileDetail/CamionnageLimitePoids/${id}`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileDetailV2apiCamionnagePontBarreRequest = (
  {
    id,
    language,
  }: {
    id: number;
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseBaseData, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseBaseData, ResponseError>(
    {
      url: `/${language}/api/v2/mobileDetail/CamionnagePontBarre/${id}`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileDetailV2apiChantierMajeurRequest = (
  {
    id,
    language,
  }: {
    id: number;
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseBaseData, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseBaseData, ResponseError>(
    {
      url: `/${language}/api/v2/mobileDetail/ChantierMajeur/${id}`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileDetailV2apiChantierMineurRequest = (
  {
    id,
    language,
  }: {
    id: number;
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseBaseData, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseBaseData, ResponseError>(
    {
      url: `/${language}/api/v2/mobileDetail/ChantierMineur/${id}`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileDetailV2apiChantierMunicipalRequest = (
  {
    id,
    language,
  }: {
    id: number;
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseBaseData, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseBaseData, ResponseError>(
    {
      url: `/${language}/api/v2/mobileDetail/ChantierMunicipal/${id}`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileDetailV2apiConditionsRequest = (
  {
    id,
    language,
  }: {
    id: number;
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseBaseData, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseBaseData, ResponseError>(
    {
      url: `/${language}/api/v2/mobileDetail/Conditions/${id}`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileDetailV2apiDetailAvertissementRequest = (
  {
    id,
    language,
  }: {
    id: number;
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseBaseData, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseBaseData, ResponseError>(
    {
      url: `/${language}/api/v2/mobileDetail/DetailAvertissement/${id}`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileDetailV2apiEvenementStandardRequest = (
  {
    id,
    language,
  }: {
    id: number;
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseBaseData, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseBaseData, ResponseError>(
    {
      url: `/${language}/api/v2/mobileDetail/EvenementStandard/${id}`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileDetailV2apiGareMontrealRequest = (
  {
    id,
    language,
  }: {
    id: number;
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseBaseData, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseBaseData, ResponseError>(
    {
      url: `/${language}/api/v2/mobileDetail/GareMontreal/${id}`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileDetailV2apiHalteRequest = (
  {
    id,
    language,
  }: {
    id: number;
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseBaseData, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseBaseData, ResponseError>(
    {
      url: `/${language}/api/v2/mobileDetail/Halte/${id}`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileDetailV2apiLibelleDataQc511Request = (
  {
    language,
  }: {
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseLibelleData, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseLibelleData, ResponseError>(
    {
      url: `/${language}/api/v2/mobileDetail/LibelleDataQc511`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileDetailV2apiLitArretRequest = (
  {
    id,
    language,
  }: {
    id: number;
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseBaseData, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseBaseData, ResponseError>(
    {
      url: `/${language}/api/v2/mobileDetail/LitArret/${id}`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileDetailV2apiMessagesRequest = (
  {
    id,
    language,
  }: {
    id: number;
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseBaseData, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseBaseData, ResponseError>(
    {
      url: `/${language}/api/v2/mobileDetail/Messages/${id}`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileDetailV2apiPointPeageRequest = (
  {
    id,
    language,
  }: {
    id: number;
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseBaseData, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseBaseData, ResponseError>(
    {
      url: `/${language}/api/v2/mobileDetail/PointPeage/${id}`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileDetailV2apiPontFederalRequest = (
  {
    id,
    language,
  }: {
    id: number;
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponsePontFederalData, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponsePontFederalData, ResponseError>(
    {
      url: `/${language}/api/v2/mobileDetail/PontFederal/${id}`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileDetailV2apiPosteFrontalierRequest = (
  {
    id,
    language,
  }: {
    id: number;
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseBaseData, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseBaseData, ResponseError>(
    {
      url: `/${language}/api/v2/mobileDetail/PosteFrontalier/${id}`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileDetailV2apiRadarPhotoFeuxRequest = (
  {
    id,
    language,
  }: {
    id: number;
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseBaseData, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseBaseData, ResponseError>(
    {
      url: `/${language}/api/v2/mobileDetail/RadarPhoto_Feux/${id}`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileDetailV2apiRadarPhotoFeuxFixeRequest = (
  {
    id,
    language,
  }: {
    id: number;
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseBaseData, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseBaseData, ResponseError>(
    {
      url: `/${language}/api/v2/mobileDetail/RadarPhoto_FeuxFixe/${id}`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileDetailV2apiRadarPhotoFixeRequest = (
  {
    id,
    language,
  }: {
    id: number;
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseBaseData, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseBaseData, ResponseError>(
    {
      url: `/${language}/api/v2/mobileDetail/RadarPhoto_Fixe/${id}`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileDetailV2apiRadarPhotoMobileRequest = (
  {
    id,
    language,
  }: {
    id: number;
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseBaseData, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseBaseData, ResponseError>(
    {
      url: `/${language}/api/v2/mobileDetail/RadarPhoto_Mobile/${id}`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileDetailV2apiRouteBlancheRequest = (
  {
    id,
    language,
  }: {
    id: number;
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseBaseData, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseBaseData, ResponseError>(
    {
      url: `/${language}/api/v2/mobileDetail/RouteBlanche/${id}`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileDetailV2apiStationMeteoRequest = (
  {
    id,
    language,
  }: {
    id: number;
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseBaseData, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseBaseData, ResponseError>(
    {
      url: `/${language}/api/v2/mobileDetail/StationMeteo/${id}`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileDetailV2apiStationnementRequest = (
  {
    id,
    language,
  }: {
    id: number;
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseBaseData, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseBaseData, ResponseError>(
    {
      url: `/${language}/api/v2/mobileDetail/Stationnement/${id}`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileDetailV2apiTraversierRequest = (
  {
    id,
    language,
  }: {
    id: number;
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseBaseData, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseBaseData, ResponseError>(
    {
      url: `/${language}/api/v2/mobileDetail/Traversier/${id}`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileDetailV2apiVillageRequest = (
  {
    id,
    language,
  }: {
    id: number;
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseBaseData, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseBaseData, ResponseError>(
    {
      url: `/${language}/api/v2/mobileDetail/Village/${id}`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileDetailV2apiZoneDegelRequest = (
  {
    language,
  }: {
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseBaseData, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseBaseData, ResponseError>(
    {
      url: `/${language}/api/v2/mobileDetail/ZoneDegel`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileV1apiCameraUrlsRequest = (
  {
    id,
    language,
  }: {
    id: number;
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseFavoritesCameras, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseFavoritesCameras, ResponseError>(
    {
      url: `/${language}/api/v4/mobile/CameraUrls/${id}`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileV1apiCarteRequest = (
  {
    language,
  }: {
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseInfoCarte, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseInfoCarte, ResponseError>(
    {
      url: `/${language}/api/v4/mobile/Carte`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileV1apiConditionsRoutieresRequest = (
  {
    language,
  }: {
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseIEnumerableConditionRoutiereMobile, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseIEnumerableConditionRoutiereMobile, ResponseError>(
    {
      url: `/${language}/api/v4/mobile/ConditionsRoutieres`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileV1apiCopyrightRequest = (
  {
    language,
  }: {
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseUrl, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseUrl, ResponseError>(
    {
      url: `/${language}/api/v4/mobile/Copyright`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileV1apiCouleursChausseeRequest = (
  {
    language,
  }: {
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseIEnumerableCouleurLigne, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseIEnumerableCouleurLigne, ResponseError>(
    {
      url: `/${language}/api/v4/mobile/CouleursChaussee`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileV1apiCurrentAdRequest = (
  {
    language,
  }: {
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseMobileAd, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseMobileAd, ResponseError>(
    {
      url: `/${language}/api/v4/mobile/CurrentAd`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileV1apiDetailAvertissementsEnVigueurRequest = (
  {
    language,
  }: {
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseIDictionaryStringIListKeyValuePairInt32String, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseIDictionaryStringIListKeyValuePairInt32String, ResponseError>(
    {
      url: `/${language}/api/v4/mobile/DetailAvertissementsEnVigueur`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileV1apiEvenementsRequest = (
  {
    language,
  }: {
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseIDictionaryStringIListEvenementMobile, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseIDictionaryStringIListEvenementMobile, ResponseError>(
    {
      url: `/${language}/api/v4/mobile/Evenements`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileV1apiFaqRequest = (
  {
    language,
  }: {
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseUrl, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseUrl, ResponseError>(
    {
      url: `/${language}/api/v4/mobile/Faq`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileV1apiLegendRequest = (
  {
    language,
  }: {
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseUrl, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseUrl, ResponseError>(
    {
      url: `/${language}/api/v4/mobile/Legend`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileV1apiLignesRequest = (
  {
    language,
  }: {
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseIEnumerableLigne, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseIEnumerableLigne, ResponseError>(
    {
      url: `/${language}/api/v4/mobile/Lignes`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileV1apiMessagesMobilesRequest = (
  {
    language,
  }: {
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseIEnumerableMessage, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseIEnumerableMessage, ResponseError>(
    {
      url: `/${language}/api/v4/mobile/MessagesMobiles`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileV1apiMunicipalitesRequest = (
  {
    language,
  }: {
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseIEnumerableDestination, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseIEnumerableDestination, ResponseError>(
    {
      url: `/${language}/api/v4/mobile/Municipalites`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileV1apiPictosRequest = (
  {
    language,
  }: {
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseIEnumerablePicto, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseIEnumerablePicto, ResponseError>(
    {
      url: `/${language}/api/v4/mobile/Pictos`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileV1apiPrivacyRequest = (
  {
    language,
  }: {
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseUrl, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseUrl, ResponseError>(
    {
      url: `/${language}/api/v4/mobile/Privacy`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileV1apiRefreshablePictosRequest = (
  {
    language,
  }: {
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseIEnumerablePicto, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseIEnumerablePicto, ResponseError>(
    {
      url: `/${language}/api/v4/mobile/RefreshablePictos`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileV1apiRegionsRequest = (
  {
    language,
  }: {
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseIEnumerableDestination, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseIEnumerableDestination, ResponseError>(
    {
      url: `/${language}/api/v4/mobile/Regions`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileV1apiRegionsRoutesRequest = (
  {
    language,
  }: {
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseIEnumerableNotificationsRegion, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseIEnumerableNotificationsRegion, ResponseError>(
    {
      url: `/${language}/api/v4/mobile/RegionsRoutes`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileV1apiStaticPictosRequest = (
  {
    language,
  }: {
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseIEnumerablePicto, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseIEnumerablePicto, ResponseError>(
    {
      url: `/${language}/api/v4/mobile/StaticPictos`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileV1apiTermeGeneralRequest = (
  {
    language,
  }: {
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseUrl, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseUrl, ResponseError>(
    {
      url: `/${language}/api/v4/mobile/TermeGeneral`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileV1apiThemesRequest = (
  {
    language,
  }: {
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseIEnumerableBoutonTheme, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseIEnumerableBoutonTheme, ResponseError>(
    {
      url: `/${language}/api/v4/mobile/Themes`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileV1apiUserGuideRequest = (
  {
    language,
  }: {
    language: string;
  },
  SWRConfig?: SWRConfig<ApiResponseUrl, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseUrl, ResponseError>(
    {
      url: `/${language}/api/v4/mobile/UserGuide`,
      method: "get",
      headers: {},
      ...axiosConfig,
    },
    SWRConfig,
  );

export const useMobileVersionV1apiAppConfigRequest = (
  {
    language,
    version,
    os,
  }: {
    language: string;
    os: string;
    version: string;
  },
  SWRConfig?: SWRConfig<ApiResponseAppConfig, ResponseError>,
  axiosConfig?: AxiosRequestConfig,
) =>
  useGetRequest<ApiResponseAppConfig, ResponseError>(
    {
      url: `/${language}/api/v1/mobileVersion/AppConfig`,
      method: "get",
      headers: {},
      params: {
        version,
        os,
      },
      ...axiosConfig,
    },
    SWRConfig,
  );

export interface MobileVersionV1apiAppConfigRequest {
  query: {
    os: string;
    version: string;
  };
}

export interface AireVerificationFreinData {
  Ecusson?: EcussonData;
  ImageUrl?: string;
  Latitude?: string;
  Longitude?: string;
  Municipalite?: string;
  Route?: string;
  Titre?: string;
}

export interface ApiMessage {
  error?: ApiMessageError;
  message?: string;
}

export type ApiMessageError = 1 | 2 | 400 | 404 | 500;

export interface ApiResponseAireVerificationFreinData {
  data?: AireVerificationFreinData;
  messages?: ApiMessage[];
}

export interface ApiResponseAppConfig {
  data?: AppConfig;
  messages?: ApiMessage[];
}

export interface ApiResponseAutre511data {
  data?: Autre511data;
  messages?: ApiMessage[];
}

export interface ApiResponseBaseData {
  data?: BaseData;
  messages?: ApiMessage[];
}

export interface ApiResponseCameraData {
  data?: CameraData;
  messages?: ApiMessage[];
}

export interface ApiResponseFavoritesCameras {
  data?: FavoritesCameras;
  messages?: ApiMessage[];
}

export interface ApiResponseIDictionaryStringIListEvenementMobile {
  data?: { [key: string]: any };
  messages?: ApiMessage[];
}

export interface ApiResponseIDictionaryStringIListKeyValuePairInt32String {
  data?: { [key: string]: any };
  messages?: ApiMessage[];
}

export interface ApiResponseIEnumerableBoutonTheme {
  data?: BoutonTheme[];
  messages?: ApiMessage[];
}

export interface ApiResponseIEnumerableConditionRoutiereMobile {
  data?: ConditionRoutiereMobile[];
  messages?: ApiMessage[];
}

export interface ApiResponseIEnumerableCouleurLigne {
  data?: CouleurLigne[];
  messages?: ApiMessage[];
}

export interface ApiResponseIEnumerableDestination {
  data?: Destination[];
  messages?: ApiMessage[];
}

export interface ApiResponseIEnumerableLigne {
  data?: Ligne[];
  messages?: ApiMessage[];
}

export interface ApiResponseIEnumerableMessage {
  data?: Message[];
  messages?: ApiMessage[];
}

export interface ApiResponseIEnumerableNotificationsRegion {
  data?: NotificationsRegion[];
  messages?: ApiMessage[];
}

export interface ApiResponseIEnumerablePicto {
  data?: Picto[];
  messages?: ApiMessage[];
}

export interface ApiResponseInfoCarte {
  data?: InfoCarte;
  messages?: ApiMessage[];
}

export interface ApiResponseLibelleData {
  data?: LibelleData;
  messages?: ApiMessage[];
}

export interface ApiResponseMobileAd {
  data?: MobileAd;
  messages?: ApiMessage[];
}

export interface ApiResponsePontFederalData {
  data?: PontFederalData;
  messages?: ApiMessage[];
}

export interface ApiResponseUrl {
  data?: Url;
  messages?: ApiMessage[];
}

export interface AppConfig {
  CurrentVersion?: string;
  EmptyCache?: string;
  Mandatory?: boolean;
  UpdateAvailable?: boolean;
}

export interface Autre511data {
  Ecusson?: EcussonData;
  ImageUrl?: string;
  Latitude?: string;
  LibelleUrl?: string;
  Longitude?: string;
  NumRegion?: string;
  Titre?: string;
  Url?: string;
}

export interface BaseData {
  Ecusson?: EcussonData;
  ImageUrl?: string;
  Latitude?: string;
  Longitude?: string;
  Titre?: string;
}

export interface BoutonTheme {
  Active?: boolean;
  ImageUrl?: string;
  Libelle?: string;
  Theme?: string;
}

export interface CameraData {
  Ecusson?: EcussonData;
  Id?: string;
  ImageUrl?: string;
  IsVideo?: boolean;
  Latitude?: string;
  Longitude?: string;
  MsgDirection?: string;
  Nom?: string;
  SourceImage?: string;
  SourceMiniature?: string[];
  SourceVideo?: string;
  Titre?: string;
}

export interface ConditionRoutiereMobile {
  PointVisibilite?: string;
  VisibilityColor?: CouleurMobile;
}

export interface CouleurLigne {
  Categorie?: string;
  CouleurChaussee?: CouleurMobile;
  Id?: string;
  ZIndex?: number;
}

export interface CouleurMobile {
  A?: number;
  B?: number;
  G?: number;
  L?: number;
  R?: number;
}

export interface Destination {
  Lat?: number;
  Long?: number;
  Name?: string;
  Zoom?: number;
}

export interface EcussonData {
  Background?: string;
  FontSize?: number;
  IconUrl?: string;
  ImageSize?: number;
  Label?: string;
  SubIconUrl?: string;
}

export interface EvenementMobile {
  IsVisible?: boolean;
  Lignes?: Ligne[];
  Pictos?: Picto[];
}

export interface FavoritesCameras {
  CameraImageUrl?: string;
  CameraUrl?: string;
  DetailUrl?: string;
  Id?: string;
  IsLoaded?: boolean;
  IsVideo?: boolean;
  Location?: string;
}

export interface IRegionsAccordionViewModel {
  IsAllToggled?: boolean;
  Region?: NotificationsRegion;
  RightImage?: string;
  Routes?: NotificationsRoute[];
}

export interface InfoCarte {
  TypePictos?: TypePicto[];
}

export interface KeyValuePairInt32String {
  key?: number;
  value?: string;
}

export interface LibelleData {
  LibelleA?: string;
  LibelleAlloTram?: string;
  LibelleCause?: string;
  LibelleChaussee?: string;
  LibelleConsequences?: string;
  LibelleDe?: string;
  LibelleDebarcadere?: string;
  LibelleDebut?: string;
  LibelleDepartConvoi?: string;
  LibelleDescription?: string;
  LibelleDetour?: string;
  LibelleDirection?: string;
  LibelleDuree?: string;
  LibelleEnVigueurDepuis?: string;
  LibelleEntrave?: string;
  LibelleFin?: string;
  LibelleInformation?: string;
  LibelleLigneDeTrain?: string;
  LibelleLimiteDeCharge?: string;
  LibelleLocalisation?: string;
  LibelleMiseAJour?: string;
  LibelleMunicipalite?: string;
  LibelleObstacle?: string;
  LibelleRadarPhotoDisponible?: string;
  LibelleRoute?: string;
  LibelleServiceTraversier?: string;
  LibelleStationnements?: string;
  LibelleStatut?: string;
  LibelleStructure?: string;
  LibelleSupportVelos?: string;
  LibelleTransportCollectif?: string;
  LibelleVisibilite?: string;
  MiseAJourConditionsRoutieres?: string;
}

export interface Ligne {
  Categorie?: string;
  CouleurChaussee?: CouleurMobile;
  Id?: string;
  IsHorsSaison?: boolean;
  Points?: Point[];
  StrokeWidth?: number;
  ZIndex?: number;
}

export interface Message {
  Date?: string;
  DateAffichee?: string;
  Description?: string;
  Id?: number;
  Unread?: boolean;
}

export interface MobileAd {
  Duration?: number;
  RedirectUrl?: string;
  Url?: string;
}

export interface NotificationsRegion {
  Id?: number;
  Nom?: string;
  Routes?: NotificationsRoute[];
}

export interface NotificationsRoute {
  Id?: number;
  IsNotificationsEnabled?: boolean;
  Type?: string;
}

export interface Picto {
  A?: string;
  B?: string;
  C?: Point;
  Z?: string;
}

export interface Point {
  A?: number;
  B?: number;
}

export interface PontFederalData {
  Ecusson?: EcussonData;
  ImageUrl?: string;
  InfoPont?: UriData;
  Latitude?: string;
  Longitude?: string;
  Nom?: string;
  Titre?: string;
}

export interface TypePicto {
  Categorie?: string;
  IsRefreshable?: boolean;
  TypePicto?: string;
}

export interface UriData {
  Item?: string;
  Text?: string;
  UriDictionnary?: { [key: string]: any };
  UrlLinkImage?: string;
}

export interface Url {
  UrlServer?: string;
}
