/* eslint-disable @typescript-eslint/explicit-module-boundary-types */
/* eslint-disable @typescript-eslint/no-explicit-any */
import { SWRConfig, useGetRequest } from "./useGetRequest";
import { ResponseError } from "../types";
import { AxiosRequestConfig, AxiosResponse } from "axios";
import { SWRMutationConfig, useMutationRequest } from "src/request/useMutationRequest";

/*
 *  this file is generated by @openapi-integration/swr-request-generator.
 *  please do not modify it manually.
 */
export const useAnotherUserProfileInformationRequest = (
  {
    AnotherAuthorities,
    anotherUserId,
    anotherUserName,
  }: {
    AnotherAuthorities: string;
    anotherUserId: string;
    anotherUserName: string;
  },
  mutationConfig?: SWRMutationConfig<
    AnotherUserProfileInformationRequest,
    AxiosResponse<AnotherAttachmentBo>,
    ResponseError
  >,
  axiosConfig?: AxiosRequestConfig,
) =>
  useMutationRequest<AnotherUserProfileInformationRequest, AxiosResponse<AnotherAttachmentBo>, ResponseError>({
    url: `/`,
    method: "post",
    headers: {
      AnotherAuthorities: AnotherAuthorities,
      "Another-User-Id": anotherUserId,
      "Another-User-Name": anotherUserName,
      "Content-Type": "multipart/form-data",
    },
    mutationConfig,
    axiosConfig,
  });

export interface AnotherUserProfileInformationRequest {
  body: FormData;
}

export interface AnotherAttachmentBo {
  authorName?: string;
  createdDate?: number;
  fileName?: string;
  id?: string;
  mimeType?: string;
  path?: string;
}
