on:
  push:
  pull_request:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node v20.11.1
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.1

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.6
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Lint check
        run: pnpm run lint

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm run test:cov

      #      - name: Update Coverage Badge
      #        uses: we-cli/coverage-badge-action@main
      - name: Get Coverage Summary
        id: get-summary
        shell: bash
        run: |
          COV=$(node -p 'require(`./coverage/coverage-summary.json`).total.lines.pct')
          echo "coverage=$COV" >> $GITHUB_OUTPUT

      # - name: Checkout gh-pages
      #   uses: actions/checkout@v3
      #   with:
      #     ref: gh-pages

      - name: Create Badges
        shell: bash
        run: |
          npm i -g badgen-cli
          export COV=${{ steps.get-summary.outputs.coverage }}
          COLOR=$(node -p '+process.env.COV >= 90 ? `green` : `orange`')
          mkdir -p badges
          badgen -j coverage -s $COV% -c $COLOR > badges/coverage.svg

      - name: Deploy Badges
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update badges [skip ci]"
          skip_fetch: true
          skip_checkout: true

      # Without this, will get Error:
      # Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/coverage-badge-action/coverage-badge-action/action.yml'.
      # Did you forget to run actions/checkout before running your local action?
      - name: Checkout Back
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
